### ISSUE TITLE
Production + testing?

### ISSUE THREAD

**Issue by drozzy** [exponentially/helios_aggregate#1]
Just curious if this is used in production somewhere?

Also, what are your recommendations on testing? E.g. can we test that a given command produces a given event?

**Comment by mjaric** [comment]
Hi @drozzy 

It is not yet in production. It is not yet meant to be used in production, since pipeline is not completed 100% as we originally intended to. 

The idea is to test if command produces desired events without need to start any GenServer that could host aggregate. There is example in test folder that best describes how we think it should be done. %Context{} should be bridge between aggregate internals and command execution schedule, but allows you to plug anything that by your opinion should not find its place inside your aggregate handler. This makes life easier to test business logic, since it would be free from any code that doesn't make sense to mock or that mock is so dumb so it would be easier to use `assign` rather then creating whole new module that implements some `behaviour` to do such simple task.  So while testing just create %Context{} and pass it to aggregate command handler along with command. You can add other plugs that will be executed before aggregate handler. The idea is to plug any infrastructure stuff or pre handling logic in form of plugs. Like phoenix does for your controllers.

Commands are rather labelled than asking you to write modules that defines struct, so command or say parameters can be ordinary map. But you are not limited to such workflow, one could create facade and router that accepts defined struct and use `cmd.__struct__` as label for command then overwrite handle in aggregate to define how command is mapped to concrete aggregate command handler function. 

So there is plenty freedom to do thing as you would like but still giving you ability to quickly "get to the point" :). Anyhow, this pattern is already present in phoenix and when all blocks are done, it shouldn't be hard to quickly get familiar with this lib.  

There will be another hex package that will offer GenServer capable to receive commands and execute it for you with builtin recovery procedure. But that is still work in progress.

**Comment by drozzy** [comment]
Looking forward to it. Currently there is only commanded - so I'm hoping you guys provide some competition (which is always good!)

**Comment by mjaric** [comment]
Depending what is your stack, maybe you could check extreme_system. It is in production for 3 years tho docs are really bad :)
